# Generated by Django 5.0.7 on 2024-07-17 11:25

from django.db import migrations

def create_data(apps, schema_editor):
    Applicant = apps.get_model('applicants', 'ApplicantDetails')
    Applicant(fullname="Ismail Zaffar", email="ismail@zaffar.com", phonenumber=7421354393, skill_1="Problem-Solving", skill_2="Adaptability", skill_3="Time-Management", skill_4="Creativity", skill_5="Negotiation", qualifications="MSci", preferences="Software developer")
    Job = apps.get_model('applicants', 'JobListings')
    Job(jobtitle="Summer Intern", companyname="Ventura Limited", salary=32000.0, jobdescription="Fancy a new job with new perks and a fresh new office? Apply for an internship position at Ventura Limited, where you will be expected to make coffee, deliver papers etc.", dateposted=2024/6/27, location="123 Harbor Rd, Milton Keynes, MK29PL")

class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
