# Generated by Django 5.0.7 on 2024-08-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_alter_joblistings_dateposted_applicantlogindetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantdetails',
            old_name='userid',
            new_name='id',
        ),
    ]
