# Generated by Django 5.0.7 on 2024-08-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_rename_userid_applicantdetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
