# Generated by Django 5.0.7 on 2024-08-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_alter_applicantdetails_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
