# Generated by Django 5.0.7 on 2024-08-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_alter_applicantdetails_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ApplicantLoginDetails',
        ),
    ]
