# Generated by Django 5.0.7 on 2024-08-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0008_alter_applicantdetails_cv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvfile', models.FileField(upload_to='cvs/')),
            ],
        ),
    ]
