# Generated by Django 5.0.7 on 2024-08-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0010_delete_files_alter_applicantdetails_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
